#!/usr/bin/env python3
"""
check_article_corpus.py — CI gate for the 1,400+ article HTML corpus.

WHY THIS EXISTS
This began as a regression gate rather than a cleanliness gate. When it was written, 449
articles were already damaged — mostly truncated by writers that ran before safe_write.py
was wired in — and a gate demanding cleanliness would have been red on every build from
day one. A permanently-red gate is one everyone learns to ignore, which is the exact
failure mode that let the truncation bug run for months.

So a committed baseline recorded the damage that already existed, and the build failed
only when a file got worse than its baseline, or when a file with no baseline entry was
anything other than clean. Existing damage was paid down at leisure; new damage was
impossible.

**The baseline is now empty.** Every one of the 1,461 articles is clean, so "no file may be
worse than its baseline" and "no file may be damaged" are the same statement, and this is a
cleanliness gate without a line of it changing.

The one way that could quietly unwind is a careless --update-baseline re-recording fresh
damage as the new floor. That is now refused: the baseline can only ever be moved down.
--allow-new-damage overrides it, deliberately loudly, if damage ever has to be
grandfathered again.

USAGE
    python3 check_article_corpus.py                   # CI gate; exit 1 on any damage
    python3 check_article_corpus.py --update-baseline # re-record after repairs
"""
from __future__ import annotations

import json
import os
import sys

from check_site_integrity import html_severity, severity_regressions

HERE = os.path.dirname(os.path.abspath(__file__))
BASELINE = os.path.join(HERE, "tests", "corpus_baseline.json")


def scan() -> dict[str, dict]:
    """Severity of every damaged HTML file, keyed by filename. Clean files are omitted."""
    out: dict[str, dict] = {}
    for name in sorted(os.listdir(HERE)):
        if not name.endswith(".html"):
            continue
        with open(os.path.join(HERE, name), encoding="utf-8", errors="replace") as fh:
            sev = html_severity(fh.read())
        if any(sev.values()):
            out[name] = {k: int(v) for k, v in sev.items()}
    return out


def load_baseline() -> dict[str, dict]:
    if not os.path.exists(BASELINE):
        return {}
    with open(BASELINE, encoding="utf-8") as fh:
        return json.load(fh)["files"]


def write_baseline(current: dict[str, dict]) -> None:
    os.makedirs(os.path.dirname(BASELINE), exist_ok=True)
    payload = {
        "_comment": (
            "Known-damaged HTML files and how damaged they are. Generated by "
            "check_article_corpus.py --update-baseline. Files absent from this list "
            "must be clean. Numbers may only go DOWN; the CI gate fails if any rise."
        ),
        "files": current,
    }
    with open(BASELINE, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")


def regressions(baseline: dict[str, dict], current: dict[str, dict]) -> list[str]:
    """One message per file that is worse than the baseline records it."""
    out: list[str] = []
    for name, sev in sorted(current.items()):
        worse = severity_regressions(baseline.get(name, {}), sev)
        if worse:
            kind = "regressed" if name in baseline else "newly damaged"
            out.append(f"{name} ({kind}): " + "; ".join(worse))
    return out


def main() -> int:
    current = scan()
    baseline = load_baseline()
    failures = regressions(baseline, current)

    if "--update-baseline" in sys.argv:
        # The baseline may only ever move DOWN. Re-recording fresh damage as the new floor
        # is the one way a green gate could quietly stop meaning anything, so it takes an
        # explicit flag rather than a habit.
        if failures and "--allow-new-damage" not in sys.argv:
            print(f"REFUSING to update the baseline — {len(failures)} file(s) are worse "
                  f"than it already records:")
            for f in failures:
                print("  -", f)
            print("\nRepair them, or pass --allow-new-damage to grandfather the damage "
                  "deliberately.")
            return 1
        write_baseline(current)
        print(f"baseline updated: {len(current)} damaged files recorded -> {BASELINE}")
        return 0

    fixed = sorted(set(baseline) - set(current))

    print(f"scanned: {len(os.listdir(HERE))} entries | damaged now: {len(current)} "
          f"| damaged at baseline: {len(baseline)}")
    if fixed:
        print(f"repaired since baseline: {len(fixed)} "
              f"(run --update-baseline to lock the improvement in)")

    if failures:
        print(f"\nFAIL — {len(failures)} file(s) got worse:")
        for f in failures:
            print("  -", f)
        return 1

    if not baseline:
        print(f"PASS — all {len(os.listdir(HERE))} entries scanned, zero damaged HTML files.")
    else:
        print("PASS — no HTML file is more damaged than its baseline.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
