#!/usr/bin/env python3
"""
check_article_corpus.py — CI gate for the 1,400+ article HTML corpus.

WHY THIS EXISTS
`check_site_integrity.py` answers "is the site clean?" and the honest answer is
no: 449 articles are still damaged, most of them truncated by writers that ran
before safe_write.py was wired in. A gate that demands cleanliness would be red
on every build from day one, and a permanently-red gate is a gate everyone learns
to ignore.

So this gates on *regression* instead. A committed baseline records the damage
that already exists; the build fails only when a file gets worse than its
baseline, or when a file with no baseline entry is anything other than clean.
That makes the invariant enforceable today: existing damage is grandfathered and
can be paid down at leisure, but no change may introduce new corruption.

As files are repaired, refresh the baseline (--update-baseline) so the repaired
state becomes the new floor and can never silently regress.

USAGE
    python3 check_article_corpus.py                   # CI gate; exit 1 on regression
    python3 check_article_corpus.py --update-baseline # re-record after repairs
"""
from __future__ import annotations

import json
import os
import sys

from check_site_integrity import html_severity, severity_regressions

HERE = os.path.dirname(os.path.abspath(__file__))
BASELINE = os.path.join(HERE, "tests", "corpus_baseline.json")


def scan() -> dict[str, dict]:
    """Severity of every damaged HTML file, keyed by filename. Clean files are omitted."""
    out: dict[str, dict] = {}
    for name in sorted(os.listdir(HERE)):
        if not name.endswith(".html"):
            continue
        with open(os.path.join(HERE, name), encoding="utf-8", errors="replace") as fh:
            sev = html_severity(fh.read())
        if any(sev.values()):
            out[name] = {k: int(v) for k, v in sev.items()}
    return out


def load_baseline() -> dict[str, dict]:
    if not os.path.exists(BASELINE):
        return {}
    with open(BASELINE, encoding="utf-8") as fh:
        return json.load(fh)["files"]


def write_baseline(current: dict[str, dict]) -> None:
    os.makedirs(os.path.dirname(BASELINE), exist_ok=True)
    payload = {
        "_comment": (
            "Known-damaged HTML files and how damaged they are. Generated by "
            "check_article_corpus.py --update-baseline. Files absent from this list "
            "must be clean. Numbers may only go DOWN; the CI gate fails if any rise."
        ),
        "files": current,
    }
    with open(BASELINE, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
        fh.write("\n")


def main() -> int:
    current = scan()

    if "--update-baseline" in sys.argv:
        write_baseline(current)
        print(f"baseline updated: {len(current)} damaged files recorded -> {BASELINE}")
        return 0

    baseline = load_baseline()
    failures: list[str] = []

    for name, sev in sorted(current.items()):
        worse = severity_regressions(baseline.get(name, {}), sev)
        if worse:
            kind = "regressed" if name in baseline else "newly damaged"
            failures.append(f"{name} ({kind}): " + "; ".join(worse))

    fixed = sorted(set(baseline) - set(current))

    print(f"scanned: {len(os.listdir(HERE))} entries | damaged now: {len(current)} "
          f"| damaged at baseline: {len(baseline)}")
    if fixed:
        print(f"repaired since baseline: {len(fixed)} "
              f"(run --update-baseline to lock the improvement in)")

    if failures:
        print(f"\nFAIL — {len(failures)} file(s) got worse:")
        for f in failures:
            print("  -", f)
        return 1

    print("PASS — no HTML file is more damaged than its baseline.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
